name: 03. Export & Commit

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Solution to export'
        required: true
        default: 'ALMDemo'
      solution_description:
        description: 'Commit message'
        required: true
        default: ''
      related_to_issue:
        description: 'Related to issue e.g. #1, #2, #3'
        required: false
        default: ''
      type_of_import:
        description: 'Upgrade or Update'
        type: 'choice'
        required: true
        options: 
        - 'upgrade'
        - 'update'
        default: 'update'
      branch:
        description: 'Branch to commit to'
        type: 'choice'
        required: true
        options: 
        - 'main'
        - 'hotfix'
        

jobs:
  export-and-create-pr:
    runs-on: ubuntu-latest

    environment:
      name: dev
      url: 'https://dev-christian.crm4.dynamics.com/'   

    env:
      RUNNER_DEBUG: 1
      SOLUTION_TARGET_FOLDER: PowerPlatform/Solutions/

    steps:
      - uses: actions/checkout@v4

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: call-deploy-workflow
          client-payload: '{"solution_name": "${{ github.event.inputs.solution_name }}", "type_of_import": "${{ github.event.inputs.type_of_import }}"}'
