name: 02. Build and Deploy to Test

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  
env:
  RUNNER_DEBUG: 1
  SOLUTION_EXPORTED_FOLDER: out/exported/
  SOLUTION_FOLDER: out/solutions/
  SOLUTION_TARGET_FOLDER: solutions/
  SOLUTION_TARGET_FOLDER_NAME: ALMDemo

jobs:
  convert-to-managed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1
      
      - name: Print PR merge commit message
        run: echo "Commit message= ${{ github.event.head_commit.message }}"

      - name: Print solution name
        run: echo "Solution name is ${{ env.solution_name }}"
