name: Build and Deploy to Test

on:
  push:
    branches:
      - develop
      
env:
  RUNNER_DEBUG: 1
  SOLUTION_EXPORTED_FOLDER: out/exported/
  SOLUTION_FOLDER: out/solutions/
  SOLUTION_TARGET_FOLDER: solutions/
  SOLUTION_TARGET_FOLDER_NAME: ALMDemo

jobs:
  convert-to-managed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Extract solution name from branch name
        id: extract-solution
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          # Ekstraher verdien etter "feature/"
          SOLUTION_NAME="${BRANCH_NAME#feature/}"
          echo "solution_name=${SOLUTION_NAME}" >> $GITHUB_ENV

      - name: Print solution name
        run: echo "Solution name is ${{ env.solution_name }}"
