name: Export from Dev

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Solution to export'
        required: true
        default: 'ALM basis'
        options:
          - 'ALM basis'
          - 'Kommer flere'
      #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder:
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solutions/

permissions:
  contents: write
  
jobs:
  export-from-dev:
    runs-on: windows-latest
    
    env:
      RUNNER_DEBUG: 1
      
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          environment-url: ${{ vars.ENVIRONMENTURL }}
          app-id: ${{ vars.CLIENTIDALMDEV }}
          client-secret: ${{ secrets.CLIENTSECRETALMDEV }}
          tenant-id: ${{ vars.TENANTID }}
