name: Export and create PR to develop

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Solution to export'
        required: true
        default: 'ALMDemo'
      solution_version:
        description: 'Version of the solution'
        required: true
        default: '1.0.0.0'

env:
  RUNNER_DEBUG: 1
  SOLUTION_EXPORTED_FOLDER: out/exported
  SOLUTION_FOLDER: out/solutions
  SOLUTION_TARGET_FOLDER: solutions

jobs:
  export-and-unpack:
    runs-on: windows-latest
      
    steps:
      - uses: actions/checkout@v4

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: ${{ vars.ENVIRONMENTURL }}
          app-id: ${{ vars.CLIENTIDALMDEV }}
          client-secret: ${{ secrets.CLIENTSECRETALMDEV }}
          tenant-id: ${{ vars.TENANTID }}

      - name: export-solution action
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.ENVIRONMENTURL }}
          app-id: ${{ vars.CLIENTIDALMDEV }}
          client-secret: ${{ secrets.CLIENTSECRETALMDEV }}
          tenant-id: ${{ vars.TENANTID }}
          solution-name: ${{ github.event.inputs.solution_name }}
          solution-output-file: ${{ env.SOLUTION_EXPORTED_FOLDER }}/${{ github.event.inputs.solution_name }}.zip

      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: ${{ env.SOLUTION_EXPORTED_FOLDER }}/${{ github.event.inputs.solution_name }}.zip
          solution-folder: ${{ env.SOLUTION_FOLDER }}/${{ github.event.inputs.solution_name }}
          solution-type: 'Unmanaged'
          overwrite-files: true

  feature-branch-and-pull-request:
    runs-on: windows-latest
    needs: export-and-unpack

    steps:
      - uses: actions/checkout@v4

      - name: create new branch
        run: |
          git fetch origin
          git checkout -b feature/${{ github.event.inputs.solution_name }}
          git push origin feature/${{ github.event.inputs.solution_name }}

      - name: copy solution files to target folder
        run: |
          mkdir -p ${{ env.SOLUTION_TARGET_FOLDER }}/${{ github.event.inputs.solution_name }}
          cp -r ${{ env.SOLUTION_FOLDER }}/${{ github.event.inputs.solution_name }}/* ${{ env.SOLUTION_TARGET_FOLDER }}/${{ github.event.inputs.solution_name }}

      - name: commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ env.SOLUTION_TARGET_FOLDER }}/${{ github.event.inputs.solution_name }}
          git commit -m "Exported and unpacked solution ${{ github.event.inputs.solution_name }} version ${{ github.event.inputs.solution_version }}"
          git push origin feature/${{ github.event.inputs.solution_name }}


      - name: create PR to develop
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature/${{ github.event.inputs.solution_name }}
          base: develop
          title: 'Exported and unpacked solution ${{ github.event.inputs.solution_name }}'
          body: 'This PR includes the latest export of the solution ${{ github.event.inputs.solution_name }} from Power Platform.'
          draft: false
