name: 01. Export and create PR to develop

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Solution to export'
        required: true
        default: 'ALMDemo'
      type_of_import:
        description: 'Upgrade or Update'
        type: 'choice'
        required: true
        options: 
        - 'upgrade'
        - 'update'
        default: 'update'
      branch:
        description: 'Branch to commit to'
        type: 'choice'
        required: true
        options: 
        - 'develop'
        - 'hotfix'
      solution_description:
        description: 'Solution description'
        required: false
        default: ''
      type_of_solution:
        description: 'Label'
        type: 'choice'
        required: false
        options: 
        - 'accces-task'
        - 'development-task'
        - 'bug'
      related_to_issue:
        description: 'Related to issue'
        required: false
        default: '#'

jobs:
  export-and-create-pr:
    runs-on: ubuntu-latest
    
    env:
      RUNNER_DEBUG: 1
      #SOLUTION_EXPORT_FOLDER: out/export/
      SOLUTION_FOLDER: out/solutions/
      SOLUTION_TARGET_FOLDER: solutions/
      
    steps:
      - uses: actions/checkout@v4

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: ${{ vars.ENVIRONMENTURL }}
          app-id: ${{ vars.CLIENTIDALMDEV }}
          client-secret: ${{ secrets.CLIENTSECRETALMDEV }}
          tenant-id: ${{ vars.TENANTID }}

      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date -u +"%d%m%YT%H%M")" >> $GITHUB_ENV

      - name: Export Solution - Unmanaged
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.ENVIRONMENTURL }}
          app-id: ${{ vars.CLIENTIDALMDEV }}
          client-secret: ${{ secrets.CLIENTSECRETALMDEV }}
          tenant-id: ${{ vars.TENANTID }}
          solution-name: ${{ github.event.inputs.solution_name }}
          solution-output-file: ${{runner.temp}}/exported/${{ github.event.inputs.solution_name }}.zip
          managed: false
          run-asynchronously: true
          overwrite: true

      - name: Export Solution - Managed
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.ENVIRONMENTURL }}
          app-id: ${{ vars.CLIENTIDALMDEV }}
          client-secret: ${{ secrets.CLIENTSECRETALMDEV }}
          tenant-id: ${{ vars.TENANTID }}
          solution-name: ${{ github.event.inputs.solution_name }}
          solution-output-file: ${{runner.temp}}/exported/${{ github.event.inputs.solution_name }}_managed.zip
          managed: true
          run-asynchronously: true
          overwrite: true

      - name: Unpack solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: ${{runner.temp}}/exported/${{ github.event.inputs.solution_name }}.zip
          solution-folder: ${{ env.SOLUTION_FOLDER }}/${{ github.event.inputs.solution_name }}
          solution-type: 'Both'
          overwrite-files: true

      - name: Prepare for PR
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          branch-name: 'feature/${{ github.event.inputs.solution_name }}-${{ env.timestamp }}'
          solution-folder: ${{ env.SOLUTION_FOLDER }}/${{ github.event.inputs.solution_name }}
          solution-target-folder: ${{ env.SOLUTION_TARGET_FOLDER }}/${{ github.event.inputs.solution_name }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true

      # Legg til sjekk for branch --diff, stopp om like og slett branch
      # finn en måte å øke versjonsnummeret på
      - name: Create PR to develop
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Pull request ${{ github.event.inputs.type_of_import }} ${{ github.event.inputs.solution_name }}'
          branch: 'feature/${{ github.event.inputs.solution_name }}-${{ env.timestamp }}'
          base: develop
          title: '*do not edit* Export and commit: ${{ github.event.inputs.type_of_import }} ${{ github.event.inputs.solution_name }}'
          body: |
            Description: ${{ github.event.inputs.solution_description }}
            Label: ${{ github.event.inputs.type_of_solution }}
            Issue: fixes ${{ github.event.inputs.type_of_solution }}
            Import: ${{ github.event.inputs.type_of_import }}
          draft: false
