name: 04. test Export From DEV
on:
  workflow_dispatch:

jobs:
  Export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: ${{ vars.ENVIRONMENTURL }}
          app-id: ${{ vars.CLIENTIDALMDEV }}
          client-secret: ${{ secrets.CLIENTSECRETALMDEV }}
          tenant-id: ${{ vars.TENANTID }}
          solution-name: ALMDemo
        
      - name: Export Solution - Unmanaged
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.ENVIRONMENTURL }}
          app-id: ${{ vars.CLIENTIDALMDEV }}
          client-secret: ${{ secrets.CLIENTSECRETALMDEV }}
          tenant-id: ${{ vars.TENANTID }}
          solution-name: ALMDemo
          solution-output-file: "${{runner.temp}}/exported/ALMDemo.zip"
          managed: false
          run-asynchronously: true
          overwrite: true

      - name: Export Solution - Managed
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.ENVIRONMENTURL }}
          app-id: ${{ vars.CLIENTIDALMDEV }}
          client-secret: ${{ secrets.CLIENTSECRETALMDEV }}
          tenant-id: ${{ vars.TENANTID }}
          solution-name: ALMDemo
          solution-output-file: "${{runner.temp}}/exported/ALMDemo_managed.zip"
          managed: true
          run-asynchronously: true
          overwrite: true
          
      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: '${{runner.temp}}/exported/ALMDemo.zip'
          solution-folder: 'PowerPlatform/Solutions/ALMDemo/Test'
          solution-type: 'Both'
          overwrite-files: true
      - name: Create new branch
        run: |
          git fetch origin
          git checkout -b feature/Test
          git push origin feature/Test

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add 'PowerPlatform/Solutions/ALMDemo/Test' --all
          git commit -m "Export and commit: Test"
          git push origin feature/Test
